### ISSUE TITLE
Mapbox freezes, chunks missing from display, logs errors

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#1508]
## Environment

- Xcode version: 13.4
- iOS version: 15.5
- Devices affected: iPhone 7
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

After panning the map around for 10 seconds or so, tilting, etc., the display stops updating, parts of the scene are not rendered, and the following error is printed constantly:

2022-08-02 18:55:15.692638-0700 Peakbagger[85154:4540094] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)

Here's a screenshot with most of the map missing:

![Screen Shot 2022-08-02 at 6 55 10 PM](https://user-images.githubusercontent.com/2266354/182507501-ee85bf32-0ea0-40da-a591-0a0d133730e9.png)

This did not happen with Maps SDK 10.6.0 (which I'm obviously reverting to).

After trying this a few more times, it seems to happen immediately upon going to high tilt.  Here's a video:

https://user-images.githubusercontent.com/2266354/182508233-243f4649-364b-4b12-a34b-2f04bbfec493.mp4

**Comment by ZiZasaurus** [comment]
@akirmse thank you for reporting. At the moment, I am unable to reproduce this behavior. Can you please provide me with the following information:

- How many markers/ objects are you adding to your map? Are they being added at runtime?
- Does this behavior occur with any of the other mapbox styles?
- Are you able to share a minimal test project you can share that reproduces this behavior?

**Comment by akirmse** [comment]
- Maybe 200 markers between points and polylines, which are all added at
runtime.

- My app doesn't use any other mapbox styles.

- I don't have a test project.  I can temporarily add you to my github repo
if you want to try to build it yourself and promise to delete the code
afterward.  You'd need to upgrade the Podfile to Mapbox 10.7.0.

Note that this behavior is new in 10.7.0.  I've never seen it before going
back to 10.0.

**Comment by Gnative** [comment]
I'm also seeing this on:

iPhone 7 on device
iOS - 15.6
Maps SDK Version - 10.7.0

Reverting to Maps SDK Version - 10.6 is fine. 

Happens when initialising a 3D view and tilting the view as explained in the original comment above - standard outdoor style from Mapbox studio and no extra layers/symbols added. Works fine in the iOS simulator. 

![IMG_5391](https://user-images.githubusercontent.com/1758875/183897159-1c8a9de0-6623-4850-bfbf-a59a82790bd3.PNG)

https://user-images.githubusercontent.com/1758875/183897177-9effcda2-634f-41c8-b58b-e1dcefaa35cb.MP4

**Comment by ZiZasaurus** [comment]
Thanks for sharing. Are you experiencing this issue on 10.7.0 stable? I tested with this version and panned for a few minutes and was unable to reproduce. If so, can you please share a minimum test case that reproduces this behavior so we can investigate further?

**Comment by akirmse** [comment]
@ZiZasaurus Are you trying on iPhone 7 hardware?  Both of us saw the problem there.

**Comment by akirmse** [comment]
Can we get an update on this please?  The bug is still present in 1.8.1, and thus I'm stuck on 1.6.0.  I've been able to move to 1.8.0 on Android.

**Comment by ZiZasaurus** [comment]
@akirmse my apologies for missing this. Did you mean v10.8.1? You mentioned only seeing this on iPhone 7 hardware. Is this still the case?

**Comment by akirmse** [comment]
Yes, sorry, 10.8.1 (and 10.8.0 on Android).

I don't have any other iPhones, unfortunately.  But given that the other reporter was also on iPhone 7, that seems suspicious and worth testing.

**Comment by ZiZasaurus** [comment]
@akirmse I was just able to reproduce on an iPhone 7 on 10.8.1 and will bring this behavior to the team for further investigation. 

```
2022-09-15 01:22:44.691426-0400 Examples[21460:702170] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
```
Pardon the video quality...
https://user-images.githubusercontent.com/44972592/190322274-474aced7-c176-4cfe-8ec4-27971858ee9a.mov

**Comment by RodrigoSAlves** [comment]
@ZiZasaurus Thanks for taking a look. Any ETA on a potential fix for this?

**Comment by akirmse** [comment]
Hoping for an update on this.  I'm still stuck on 10.6.0 on iOS as a result.

**Comment by ZiZasaurus** [comment]
@akirmse thanks you for following up. Our team is working on resolving this issue for you. If there's any additional information you'd like to provide regarding this issue, I'd be happy to pass it along!

**Comment by Gnative** [comment]
I can report for me that i'm no longer seeing this issue on iPhone 7 with more current versions of the Maps SDK.

**Comment by ZiZasaurus** [comment]
Fantastic, @Gnative thank you for following up! @akirmse, @RodrigoSAlves can you please try on the newest version of the Maps SDK to verify this issue is resolved?

**Comment by akirmse** [comment]
I just tried 10.9.1 and it seems to work.

**Comment by ZiZasaurus** [comment]
Fantastic, yes it was resolved in 10.9.0. I will close this ticket out, but please feel free to reopen if the issue resurfaces.

**Comment by nichita-stefanita** [comment]
@ZiZasaurus we still encounter this issue on iPhone 7. Any chance to adress this?
MapBox version: 11.5.2
iOS version: 15.8
