### ISSUE TITLE
Unable to install Package in Xcode 14.0.1

### ISSUE THREAD

**Issue by rouviere** [mapbox/mapbox-maps-ios#1655]
## Environment

- Xcode version: 14.0.1
- iOS version: 12.6
- Devices affected: MacBook Pro
- Maps SDK Version: 10.8.1

## Observed behavior and steps to reproduce
I am running Xcode 14.0.1 and I am trying to add MapBox Swift Package for iOS using this link: https://github.com/mapbox/mapbox-maps-ios.git

I have been following the instructions [here](https://docs.mapbox.com/ios/maps/guides/install/#add-the-dependency):

I Created the download token (including Downloads:READ checked) and saved it to an .netrc file in my root directory in this form:

machine api.mapbox.com
login mapbox
password my_secret_token_here 
Next I created the access token and saved it to my Info.plist as

MBXAccessToken my_second_secret_token
When I attempted to add the package using the above link, I set it to

Up to Next Major Version 10.8.1
When I click Add Package it goes through the normal Fetch and download process but instead of installing properly I get the following failure notice:

![Screen Shot 2022-10-18 at 11 24 12 AM](https://user-images.githubusercontent.com/4437546/196507929-71ae9044-994e-4146-9cb5-49cecf3fd56f.png)

## Expected behavior

I expected to be able to download the necessary files and move on to building a map

## Notes / preliminary analysis

When I made my first attempt to install I had placed the .netrc in the another directory. When the download failed I moved it to the root directory and it still failed.

## Additional links and references

none.

**Comment by ZiZasaurus** [comment]
@rouviere thank you for reaching out to support. I am able to successfully install the package using the configuration you provided in Xcode 14.0.1. Can you please verify that your .netrc file has the `.` prefix and is housed in the root folder of your computer (not your Xcode project)?

**Comment by rouviere** [comment]
Hi ZiZi,

Confirmed:

**Comment by DaraAdekore** [comment]
Can confirm I'm coming across this issue as well. the .netrc file is installed and created with the appropriate credentials in the root folder. Still getting this error
<img width="270" alt="Screen Shot 2022-10-20 at 9 31 36 PM" src="https://user-images.githubusercontent.com/18224357/197112416-aa6bfac1-de78-4856-9c33-905fe506535b.png">

**Comment by DaraAdekore** [comment]
> Can confirm I'm coming across this issue as well. the .netrc file is installed and created with the appropriate credentials in the root folder. Still getting this error assuming my issue is related to OPs post. <img alt="Screen Shot 2022-10-20 at 9 31 36 PM" width="270" src="https://user-images.githubusercontent.com/18224357/197112416-aa6bfac1-de78-4856-9c33-905fe506535b.png">

My issue is resolved. I missed the "Generate credential for mapbox" line in the .netrc file

**Comment by ZiZasaurus** [comment]
@rouviere can you please create a new secret token (including the `Download:Read` scope), replace the token in your .netrc file with this token and try to install the package again? Please make sure that only the token is in the password field and that your (with no additional brackets).

**Comment by rouviere** [comment]
I created a new token and the download still fails. Wish I had better news.

**Comment by maios** [comment]
> Notes
>
> - If you need to update your packages, you can click on File > Swift Packages > Update To Latest Package Versions
> - Sometimes, artifacts cannot be resolved or errors can occur, in this case select File > Swift Packages > Reset Package Cache
> - If your Xcode crashes, delete your derived data folder

@rouviere Could you try to Reset Package Cache?

**Comment by devcanas** [comment]
Having the same issue here, this is what I get back from the package fetching failing requests:

<img width="989" alt="imagem" src="https://user-images.githubusercontent.com/20864454/198854416-36013cc1-282f-4299-9274-f92fe9d67339.png">

Have tried everything else in this page already. Any clues why the token in not being added to the request at all?

@ZiZasaurus you mentioned we should move the .netrc file to the root of the computer, do you mean the home folder "~"?
Thanks in advance 🙏

**Comment by djryanash** [comment]
I was also having this problem. Being new to iOS development (and development in general), I made a silly mistake:


I added my Secret Token to the MBXAccessToken Properties in the Info.plist file, instead of the Public Access Token.  

Sorted it out now. :)

**Comment by devcanas** [comment]
I was also able to sort it by installing Xcode 14.0.1, apparently Xcode 14.1 RC is not working

**Comment by ZiZasaurus** [comment]
@devcanas, yes the .netrc file should be housed in the home folder of the computer.

**Comment by ZiZasaurus** [comment]
@rouviere were you able to get this resolved?

**Comment by ZiZasaurus** [comment]
Closing this ticket. If you continue to experience issues with installing the dependencies, please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by gshaw** [comment]
I was having this issue with Xcode 15.3 and found that I needed to completely remove the `mapbox-common-ios` package from Xcode and then adding it again to be able to get past the failed download errors.

**Comment by kaspesi** [comment]
Still having this issue. My ~/.netrc has the same permission and information as on another machine, but still unable to download.

**Comment by drakebalma** [comment]
I am having the same issue. I have spent 5 hours straight on it has anyone found the solution?

**Comment by OdNairy** [comment]
@drakebalma If your `netrc` token is fine, you might need to cleanup SPM caches to remove the malformed server response. 
```bash
rm -rf ~/Library/Caches/org.swift.swiftpm/artifacts
```

**Comment by tib0o0o** [comment]
https://github.com/mapbox/mapbox-maps-ios/issues/1655#issuecomment-2196441536

This solution works for me
