### ISSUE TITLE
CI crashes with Mapbox SDK Version 10.9.1 + Xcode 14

### ISSUE THREAD

**Issue by Taeeun-Kim** [mapbox/mapbox-maps-ios#1779]
## Environment

- Xcode version: 14.1 (14B47b)
- iOS version: 16.1
- Maps SDK Version: 10.9.1

## Observed behavior and steps to reproduce
Run unit test with CI (in my case: Github Action)
Condition: Xcode 14, iOS 16, Mapbox SDK Version 10.9.1

## Expected behavior
`Run unit test` should work.
But it fails.

**My situation**
Xcode 14, pod Mapbox-iOS-SDK 5.9.0 <- everything is fine (locally build/run/UnitTest)
Xcode 14, pod 'MapboxMaps', '10.9.1'<- everything is fine, except run UnitTest in GitHub Action. (also with SPM same problem)

ErrorLog from GitHub Action:
———
Exit status: 65 Testing failed: App encountered an error (Test runner never began executing tests after launching. If you believe this error represents a bug, please attach the result bundle at /Users/runner/Library/Developer/Xcode/DerivedData/App-fbpimzppcxqhpqbglovtyzgdepzv/Logs/Test/App-2022.12.07_15-31-40-+0000.xcresult)
———

## Notes / preliminary analysis

code signing issues since Xcode 14
or
resource_bundles problem since Xcode 14 (https://github.com/mapbox/mapbox-maps-ios/pull/1759)

## Additional links and references
maybe useful issue links:
https://github.com/fastlane/fastlane/issues/20810#issuecomment-1337450181
https://forums.swift.org/t/xcode-14-beta-code-signing-issues-when-spm-targets-include-resources/59685

**Comment by evil159** [comment]
@Taeeun-Kim This issue is addressed in https://github.com/mapbox/mapbox-maps-ios/pull/1888, could you give it a go?

**Comment by Taeeun-Kim** [comment]
@evil159  Unfortunately I still get same error

## pod log, after pod init (to install the latest version)
in Podfile: `pod 'MapboxMaps', :git => 'https://github.com/mapbox/mapbox-maps-ios'`
——— 
Pre-downloading: `MapboxMaps` from `https://github.com/mapbox/mapbox-maps-ios`, commit `b1eb50f34b00c0d0b8590179cf8a252cfc4d4200`
——— 
and also checked manually if the changes from #1888 applied locally
![image](https://user-images.githubusercontent.com/44340864/216553653-0886ee0d-ecfc-4f37-888a-166145f985d6.png)

**Comment by Taeeun-Kim** [comment]
@evil159 
We changed some signing things and then it works now.
Thanks for your help.
